### PR TITLE
Read OIDC config from current context

### PR DESCRIPTION
**Pull request by cblims**
This PR makes dexter read OIDC configuration from current context.

### CODE REVIEW

**Comment by dkerwin** [comment]
Thank you so much for your contribution(s) to dexter. I really like the idea of using credentials already present in the kube configuration. I've reviewed your changes and would like to suggest some changes and in fact it's a pretty big change. I'm not sure what's the best way to handle this situation. I really want you to get the credits for this change. I'll put my changes right into this comment. Happy to discuss the details ;-)

```// setup and populate the OAuth2 config
func (d *dexterOIDC) createOauth2Config() error {
	// no commandline client credentials supplied
	if d.clientID == "REDACTED" && d.clientSecret == "REDACTED" {
		// no builtin defaults - let's try auto-configuration
		if defaultClientID == "" && defaultClientSecret == "" {
			log.Info("Autopilot mode - no credentials set")
			if err := d.autoConfigureOauth2Config(); err != nil {
				return errors.New(fmt.Sprintf("failed to extract oidc configuration from the kube config: %s", err))
			}
		} else if defaultClientID != "" && defaultClientSecret != "" {
			// use build-time defaults if no clientId & clientSecret was provided
			log.Info("Using builtin credentials - no credentials set")
			d.clientID = defaultClientID
			d.clientSecret = defaultClientSecret
		}
	}

	// setup oidc client context
	oidc.ClientContext(context.Background(), d.httpClient)

	// populate oauth2 config
	d.Oauth2Config.ClientID = oidcData.clientID
	d.Oauth2Config.ClientSecret = oidcData.clientSecret
	d.Oauth2Config.RedirectURL = oidcData.callback

	switch oidcData.endpoint {
	case "azure":
		d.Oauth2Config.Endpoint = microsoft.AzureADEndpoint(oidcData.azureTenant)
		d.Oauth2Config.Scopes = []string{oidc.ScopeOpenID, oidc.ScopeOfflineAccess, "email"}
	case "google":
		d.Oauth2Config.Endpoint = google.Endpoint
		d.Oauth2Config.Scopes = []string{oidc.ScopeOpenID, "profile", "email"}
	default:
		return errors.New(fmt.Sprintf("unsupported endpoint: %s", oidcData.endpoint))
	}

	return nil
}

// populate the Oauth2Config object from the kube config. Return an error when the operation failed
func (d *dexterOIDC) autoConfigureOauth2Config() error {
	// initialize the clientConfig and error variables
	var clientCfg *clientCmdApi.Config
	var err error

	// try to load the credentials from the kubeconfig specified on the commandline
	if d.kubeConfig != "" {
		clientCfg, err = clientcmd.LoadFromFile(d.kubeConfig)

		if err != nil {
			return errors.New(fmt.Sprintf("failed to load kubeconfig from %s: %s", d.kubeConfig, err))
		}
	} else {
		// try to load credentials from CurrentContext
		clientCfg, err = clientcmd.NewDefaultClientConfigLoadingRules().Load()

		if err != nil {
			return errors.New(fmt.Sprintf("failed to load kubeconfig from the default locations: %s", err))
		}
	}

	// loop through all the contexts until we find the current context
	for contextName, context := range clientCfg.Contexts {
		// find the context definition that matches the current active context
		if contextName == clientCfg.CurrentContext {
			// loop through the global authentication definitions
			for authName, authInfo := range clientCfg.AuthInfos {
				// find the authentication definition that is in use in the current context
				if authName == context.AuthInfo {
					// ensure it is oidc based
					if authInfo.AuthProvider != nil && authInfo.AuthProvider.Name == "oidc" {
						// verify that relevant keys exist
						for _, key := range []string{"client-id", "client-secret", "idp-issuer-url"} {
							if _, ok := authInfo.AuthProvider.Config[key]; !ok {
								return errors.New(fmt.Sprintf("%s is missing in kubeconfig: %s", key, err))
							}
						}

						// set client credentials and idp url based on the kubeconfig definition
						d.clientSecret = authInfo.AuthProvider.Config["client-secret"]
						d.clientID = authInfo.AuthProvider.Config["client-id"]
						idp := authInfo.AuthProvider.Config["idp-issuer-url"]

						// set endpoint based on a match on the issuer URL
						if strings.Contains(idp, "google") {
							oidcData.endpoint = "google"

						} else if strings.Contains(idp, "microsoft") {
							oidcData.endpoint = "azure"
							// TODO: tenant variable is not used. useless in regex
							re, err := regexp.Compile(`(?P<tenant>[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12})`) //uuid is tenant

							if err != nil {
								return errors.New(fmt.Sprintf("failed to extract the azure tenant from the issuer URL: %s", err))
							}

							res := re.FindStringSubmatch(idp)
							if len(res) == 1 {
								oidcData.azureTenant = res[0] // found tenant
							} else {
								return errors.New(fmt.Sprintf("failed to identify tenant ID. Found %d matches", len(res)))
							}
						}

						return nil
					}
				}
			}
		}
	}

	return errors.New("failed to auto-configure OIDC from kubeconfig")
}
```

**Comment by dkerwin** [comment]
I've also put my changes on your work in the branch autopilot (https://github.com/gini/dexter/compare/autopilot?expand=1) if you want to see the changes directly.

**Comment by cblims** [comment]
Nice work, and much more resilient code. As I mentioned in previous PR this is my first attempt to do a pull request and also my first Golang lines. Happy to contribute with ideas!

That said, you shouldn't return error on no tenant found. oidcData.azureTenant should set to "common" and continue. 

The if match on the uuid regexp will never evaluate to true as I've used parentheses around it (?P<tenant>....), the regexp will always return two elements on match. Either increase to if len(res) == 2, or better remove the parantheses and  ?P<tenant>. First element is matching part of regexp, and second element is whats matches inside each parentheses pairs.

What is next, should I update my PR with your suggestion and these two comments?

**Comment by dkerwin** [comment]
I'd appreciate if you could add my suggestions and your own fixes into the PR. So we get the best of both worlds ;-)

**Comment by dkerwin** [comment]
LGTM. Thank you!

**Pull request merged**
