### PR TITLE
Use kubeconfig as config

### PR DESCRIPTION
**Pull request by cblims**
This pull request makes dexter able to login based on configuration of current context. If oidc is configured for current context it fetches client-id, client-secret, idp-issuer-url and use it to login and get new token.

### CODE REVIEW

**Comment by dkerwin** [comment]
Can you please rebase on master? It's hard to review the change with all the extra content in there. Thank you!

**Comment by dkerwin** [comment]
Sorry to keep nagging but could you rebase this PR on the changes that have been merged into my master? This PR still has 211 files in the changelist and the vast majority was already added and in part of my master. Please let me know if I can help you in any way. Thank you!

**Comment by cblims** [comment]
Yes, please help out here. I've been fooling around with git locally and did some merge between my master and my branch. Submitting github pull request is a new experience for me, and for sure I've made a mess :)

The easiest is probably close this pull request, and I'll make a new branch and another PR? Or is there cleaner ways?

**Comment by dkerwin** [comment]
Creating a new "clean" branch and PR would be the fastest and simplest approach to this. If you are able to replicate your changes easily I would go that route. The other alternative would be to:

```
# in your branch
git remote add upstream https://github.com/gini/dexter.git
git fetch upstream
git rebase upstream/master
```

This may lead to conflicts and if you reach that stage we either have to dig deeper or fall back to the initial approach... Hope this helps

**Comment by cblims** [comment]
I've tried this road. There was a bunch of merging I've managed to get past, but I'm stuck as I can't push without pulling from my origin. Tried force...

Let's cancel this one, and I'll make a new branch and pull request.

**Pull request closed without merging**
