### PR TITLE
GitHub Support

### PR DESCRIPTION
**Pull request by mrauer**

### CODE REVIEW

**Comment by tlvenn** [comment]
It might be a good idea to update the doc and other parts of the code to add Github support in addition to Google and Azure @mrauer.

**Comment by tlvenn** [comment]
Hi @mrauer,

Did you actually test that PR ?
On my side i do end up with an error:
> Failed to write k8s config: Failed to parse token: square/go-jose: compact JWS format must have three parts

And now that I have looked into it, it seems to me that Github does not actually implement OIDC spec so it seems impossible to use it as a provider...

**Comment by dkerwin** [comment]
Thank you for this PR. I'll have a look but I agree with @tlvenn that it may not work

**Comment by dkerwin** [comment]
Hey @mrauer,

fyi: once https://github.com/gini/dexter/pull/30 is merged it becomes very easy to add new providers to dexter

**Comment by dkerwin** [comment]
Not that #30 is merged it is very easy to extend dexter with new providers. Would love to see you implement the first github provider ;-)

**Comment by tlvenn** [comment]
It's great that the PR was merged but keep in mind that until Github decides to support OIDC, it's not really possible to support it.

**Comment by dkerwin** [comment]
You are right. Given that it's not possible with Github without something like dex in the middle I'll close this PR

**Pull request closed without merging**
